services:
  app:
    image: 'shift_rc_backend:latest'
    build:
      context: .
    container_name: shift_rc_backend
    depends_on:
      - db
    ports:
      - 8085:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5435/postgres?
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres'
    container_name: db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=shift_rc
    volumes:
      - ../../volumes/shift_rc_backend_db:/var/lib/postgresql/data